### ISSUE TITLE
Any instructions for running Tensorflow.js? 

### ISSUE THREAD

**Issue by innerop** [google/node-gles#17]
Hi,

Which version of tensorflow.js is currently supported?

Is there an example somewhere of tensorflow.js running on node-gles?

Last and most key question is: does this offer any benefit over using the C version of tensorflow for nodejs (I believe there is a tensorflow native module for node out there, based on my vague recollection) For instance, does node-gles allow tensorflow.js to fully exploit the GPU (if present on the system) whereas tensorflow nodejs native module is a CPU only version? Also, what if the system has multiple GPUs, does tensorflow.js have any plans to support local distributed training or distributed inference using multiple GPUs? 

Would love to hear back soon. Thank you. This is EXCITING.

**Comment by nkreeger** [comment]
Some answers to your questions:
 
> Which version of tensorflow.js is currently supported?
We currently don't have an official supported version of TensorFlow.js. Stay tuned this is something we're working on at the moment.

> Is there an example somewhere of tensorflow.js running on node-gles?

Nothing official/stable/etc. I do have a test branch that I'm using to sort out some bugs with f16 textures: https://github.com/google/node-gles/compare/kreeger-rpi-fix?expand=1

> Last and most key question is: does this offer any benefit over using the C version of tensorflow for nodejs (I believe there is a tensorflow native module for node out there, based on my vague recollection) For instance, does node-gles allow tensorflow.js to fully exploit the GPU (if present on the system) whereas tensorflow nodejs native module is a CPU only version? Also, what if the system has multiple GPUs, does tensorflow.js have any plans to support local distributed training or distributed inference using multiple GPUs?

We do have Node.js bindings with the C library of libtensorflow. Those bindings exist in the following two packages:
* [`@tensorflow/tfjs-node`](https://www.npmjs.com/package/@tensorflow/tfjs-node) (CPU libtensorflow)
* [`@tensorflow/tfsj-node-gpu`](https://www.npmjs.com/package/@tensorflow/tfjs-node-gpu) (CUDA-only libtensorflow)

We're thinking about the messaging here since there are many options for hardware execution paths. The existing Node.js bindings enable CPU support in libtensorflow and GPU w/ CUDA with libtensorflow. The headless WebGL backend (powered by `node-gles`) will enable GPU hardware acceleration on more devices than just CUDA enabled devices. Think of devices like IoT and mobile as well as some desktop/server integration strategies. 

This is all preliminary work and hopefully we'll have something to showcase externally in the coming weeks.

**Comment by innerop** [comment]
Great info, thank you. The trajectory of this project looks amazing in that there will be great benefit if we could run TF with more than just NVIDIA GPUs, without a CUDA to OpenCL conversion. 

For the time being, given the early stage of this project, I may be better off going with  tfjs-node-gpu on top of CUDA. But only on temporary basis until node-gles is fully ready!
